services:
  wrk:
    build:
      context: .
      dockerfile: ./Dockerfile
    container_name: benchmarking
    entrypoint: ["/bin/bash"]
    tty: true
    stdin_open: true
    volumes:
      - ./:/app
    working_dir: /app
    networks:
      - external-network

networks:
  external-network:
    external: true